package.json, src/App.js, yarn.lock
Lock file changed due to installing `@material-ui/lab` for the Alert which required to update `@material-ui/core` version.
=> Metamask errors

src/App.js
=> Added help section

package-lock.json, src/App.js, src/components/Dashboard.js, src/components/NewBondForm.js, src/components/RewardCard.js, src/components/UnbondConfirmationDialog.js, src/helpers/constants.js, src/helpers/utils.js
=> Exported components and commonly used functions/constants in seperate files

package-lock.json, package.json, src/App.js, src/components/ConfirmationDialog.js, src/components/Dashboard.js, src/components/HelperMenu.js, src/components/LegacyADXSwapDialog.js, src/components/NewBondForm.js, src/components/RewardCard.js, src/helpers/constants.js, src/helpers/formatting.js
fixes #21 
fixes #27
fixes #22  
fixes #30
fixes #29
=> Enable rewards, swap ADX and fix various issues

src/App.js, src/components/NewBondForm.js, src/helpers/formatting.js
=> Fix for #32

src/App.js, src/components/ChooseWallet.js
disable if wallet connect infura id not available
=> disable if wallet connect infura id not available

package.json, src/components/SideNav.js
- adds link to landing page https://www.adex.network/staking/
- fixes an issue 'lint-staged' is not recognized as an internal or external command -> https://github.com/okonet/lint-staged/issues/420#issuecomment-558121775
=> Add Link to landing page

public/locales/en/translation.json, src/App.js, src/AppHooks.js, src/actions/actions.js, src/components/Root.js, src/components/UserData.js, src/components/cardCommon.js
- fixes:
- unspecified errors messages
- outstanding threshold for non DAI channels
- legacy channels withdraw from rewards page
- app theme on suspence
- pool total incentive APY from all active channels
=> Misc fixes

public/locales/cn/translation.json, public/locales/en/translation.json, public/locales/kr/translation.json, src/components/Root.js, src/components/StakeNowPopup.js, src/components/StatsCard.js, src/helpers/localStorage.js, src/resources/adex-logo-clean.svg, src/themeMUi.js
* adds pop up when new ADX tokens are detected - closes https://github.com/AdExNetwork/adex-staking/issues/62
- it is displayed when user has ADX balance (wallet + identity) & no bonds & once per day
=> Stake popup

src/components/LangSelect.js, src/components/Toolbar.js
=> add lang select menu

src/actions/actions.js
Didn't know its merged to master so I've pushed here
=> fix initial staking again

src/components/EmailSignUpCard.js, src/components/Gasless.js, src/components/PoolCard.js, src/components/SideNav.js, src/components/Stats.js, src/components/StatsChart.js, src/themeMUi.js
update the light theme colors and  more
=> Theme update

package-lock.json, public/locales/en/translation.json, src/AppHooks.js, src/actions/actions.js, src/components/Bonds.js, src/components/FarmCard.js, src/components/Stakings.js
added `re-bond` btn for bonds - closes  https://github.com/AdExNetwork/adex-staking/issues/55
=> Rebond pending unbonds

package-lock.json, package.json, src/actions/actions.js, src/actions/farm.js, src/actions/loyaltyPoolActions.js, src/actions/pools.js, src/components/LegacyADXSwapDialog.js, src/ethereum.js, src/helpers/constants.js
update `ethers js` pkg and prepare defaultProvider to be func later
=> update ethers and defaultProvider

public/locales/en/translation.json, public/locales/ko/translation.json, src/helpers/constants.js
update for adx farm pools until 28.12.20
=> update farm end data

jsconfig.json, src/components/Pools.js
- Add a new box: 'New to staking' on staking portal (closes #103)
- adds jsconfig for absolute imports autocomplete
=> New to staking

public/locales/en/translation.json, src/AppHooks.js, src/actions/actions.js, src/actions/v5actions.js, src/components/NewGaslessBondForm.js, src/components/Pools.js, src/components/Root.js, src/components/rootStyles.js
- adds pending transactions alert - closes #110 
- fixes gasless staking action
=> Txns alert

public/locales/en/translation.json, src/actions/loyaltyPoolActions.js, src/actions/v5actions.js, src/components/DepositForm.js, src/components/Deposits.js, src/components/StakingPoolTxnsHistory.js, src/components/Stats.js, src/helpers/constants.js
- fixed typos
- fixed validator stats
- fixed deposit/unbodnd/withdraw forms confirmations
- fixed loyalty pool stats and rewards calculation
- fixed staking pool balance and rewards calc with locked shares (pending and ready to withdraw)
=> Small fixes

public/locales/en/translation.json, src/actions/v5actions.js, src/components/Gasless.js, src/components/NewGaslessBondForm.js
* add btn for user deposit with fees for gasless address balance when it is insufficient.
=> No gasless gasless

src/components/CustomButton.js, src/components/CustomTextField.js, src/components/DepositForm.js, src/components/EmailSignUpCard.js, src/components/WithDialog.js
- Fixed Text field on Email sign-up form: 
- Fixed disabled button style, some aligns and removed close button on Deposits dialog form
- Fixed border color changes on hover and focus for input on Deposits dialog form
=> Fix: Dialog & EmailSign and custom components styles

package-lock.json, package.json, src/components/ChooseWallet.js, src/components/WalletMenu.js, src/helpers/connector.js, src/helpers/constants.js, src/resources/ambire-logo.svg
- removed trezor connector
- changed MM to browser wallet
=> Trezor fix
